version: '2'
services:
  titan:
    image: robbert229/titan-cassandra-es
    ports:
     - "8182:8182"

  cassandra:
    image: scylladb/scylla
    ports:
     - "9042:9042"
     - "9160:9160"

  elasticsearch:
    image: elasticsearch:1.6
    ports:
     - "9200:9200"
     - "9300:9300"